apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki/sign-intermediate/cert-manager
    server: http://172.28.0.1:8200
    auth:
      tokenSecretRef:
         name: my-vault-token
         key: token
